# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.mx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('tipo', models.CharField(choices=[('mo', 'Motriz'), ('vi', 'Visual'), ('au', 'Auditivo'), ('de', 'Desarrollo'), ('ot', 'Otro')], max_length=2)),
                ('severidad', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, help_text='Especifique cualquier informaci\xf3n adicional, por ejemplo atenciones especiales requeridas')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_discapacidad_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_discapacidad_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'capacidades especiales',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('calle', models.CharField(max_length=255)),
                ('numero_exterior', models.CharField(max_length=32, verbose_name='n\xfamero exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=32, verbose_name='n\xfamero interior')),
                ('colonia', models.CharField(blank=True, max_length=128)),
                ('delegacion', models.CharField(blank=True, max_length=64, verbose_name='delegaci\xf3n o municipio')),
                ('codigo_postal', localflavor.mx.models.MXZipCodeField(help_text='aa', verbose_name='c\xf3digo postal')),
                ('estado', localflavor.mx.models.MXStateField()),
                ('pais', models.CharField(default='M\xe9xico', max_length=64)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_domicilio_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_domicilio_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('calle', 'numero_exterior', 'numero_interior'),
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('rfc', localflavor.mx.models.MXRFCField(blank=True, help_text='Registro Federal de Contribuyentes', verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n social')),
                ('nombre', models.CharField(max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_organizacion_creados', to=settings.AUTH_USER_MODEL)),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='humanos.Domicilio')),
                ('domicilio_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humanos.Domicilio')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_organizacion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organizaci\xf3n',
                'verbose_name_plural': 'organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('rfc', localflavor.mx.models.MXRFCField(blank=True, help_text='Registro Federal de Contribuyentes', verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n social')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre(s) de pila')),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(blank=True, max_length=255)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='g\xe9nero')),
                ('curp', localflavor.mx.models.MXCURPField(blank=True, help_text='Clave \xdanica de Registro de Publaci\xf3n', verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255, verbose_name='lugar de nacimiento')),
                ('fecha_fallecimiento', models.DateField(blank=True, help_text='Q. E. P. D.', null=True, verbose_name='fecha de fallecimiento')),
                ('lugar_fallecimiento', models.CharField(blank=True, max_length=255, verbose_name='lugar de fallecimiento')),
                ('foto', models.FileField(blank=True, upload_to=b'')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[(None, 'Desconocido'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='grupo sangu\xedneo')),
                ('rh_sanguineo', models.NullBooleanField(choices=[(None, 'Desconocido'), (False, 'Negativo'), (True, 'Positivo')], verbose_name='RH Sangu\xedneo')),
                ('alergias', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_persona_creados', to=settings.AUTH_USER_MODEL)),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='humanos.Domicilio')),
                ('domicilio_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humanos.Domicilio')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humanos_persona_modificados', to=settings.AUTH_USER_MODEL)),
                ('responsables', models.ManyToManyField(related_name='_persona_responsables_+', to='humanos.Persona')),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='discapacidad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discapacidades', to='humanos.Persona'),
        ),
    ]
