# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.mx.models


class Migration(migrations.Migration):

    dependencies = [
        ('humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='codigo_postal',
            field=localflavor.mx.models.MXZipCodeField(help_text='aa', verbose_name='c\xf3digo postal'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_exterior',
            field=models.CharField(max_length=32, verbose_name='n\xfamero exterior'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=32, verbose_name='n\xfamero interior'),
        ),
    ]
