# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanos', '0002_preferenciacontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferenciacontacto',
            options={'verbose_name': 'preferencia de contacto', 'verbose_name_plural': 'preferencias de contacto'},
        ),
    ]
