# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamientos_como_arrendador', to='humanos.Persona', verbose_name='propiedades')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamientos_como_arrendatario', to='humanos.Persona', verbose_name='propiedades')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condominios_arrendamiento_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamientos', to='condominios.Departamento')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condominios_arrendamiento_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departamento'],
                'verbose_name_plural': 'Arrendamientos',
            },
        ),
    ]
