# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humanos', '0003_auto_20160705_2230'),
        ('seguridad', '0002_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('a_favor', models.ManyToManyField(blank=True, related_name='inciativas_a_favor', to='humanos.Persona')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_iniciativa_creados', to=settings.AUTH_USER_MODEL)),
                ('en_contra', models.ManyToManyField(blank=True, related_name='inciativas_en_contra', to='humanos.Persona')),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas_iniciadas', to='humanos.Persona')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_iniciativa_modificados', to=settings.AUTH_USER_MODEL)),
                ('neutrales', models.ManyToManyField(blank=True, related_name='inciativas_neutrales', to='humanos.Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_inicio', '-fecha_termino']},
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(db_index=True, default=datetime.datetime(2016, 7, 5, 22, 30, 31, 501384), verbose_name='fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_termino',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='iniciado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_iniciados', to='humanos.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='razon_termino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='resolucion',
            field=models.TextField(blank=True, verbose_name='resoluci\xf3n'),
        ),
    ]
