# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_auto_20160705_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='propuesta',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respuesta_a',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='a_favor',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='contrapropuesta_de',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='en_contra',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='iniciado_por',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='neutrales',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Propuesta',
        ),
    ]
