# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finanzas.models
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('clave', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_banco_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_banco_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clave', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('recurrencias', recurrence.fields.RecurrenceField()),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_contrato_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_contrato_modificados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='humanos.Persona')),
            ],
            options={
                'ordering': ['-fecha_termino', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Banco')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanos.Persona')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentabancaria_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentabancaria_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='CuentaEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanos.Organizacion')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentaempresarial_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentaempresarial_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta bancaria empresarial',
                'verbose_name_plural': 'cuentas bancarias empresariales',
            },
        ),
        migrations.CreateModel(
            name='CuentaPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanos.Persona')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentapersonal_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentapersonal_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta bancaria personal',
                'verbose_name_plural': 'cuentas bancarias personales',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_servicio', to='finanzas.Contrato')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_evaluacionservicio_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_evaluacionservicio_modificados', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_servicio', to='humanos.Persona')),
            ],
            options={
                'verbose_name': 'evaluaci\xf3n de servicio',
                'verbose_name_plural': 'evaluaciones de servicio',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_factura_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_factura_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_licitacion_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_licitacion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'licitaci\xf3n',
                'verbose_name_plural': 'licitaciones',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_proveedor_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_proveedor_modificados', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanos.Organizacion')),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('d', 'Dep\xf3sito'), ('r', 'Retiro')], max_length=1)),
                ('fecha', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=256, verbose_name='n\xfamero')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripci\xf3n')),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('monto_bruto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recibo_pdf', models.FileField(blank=True, null=True, upload_to='recibos')),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='rrecibod')),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('factura_cbd', models.FileField(blank=True, null=True, upload_to='facturas/')),
            ],
            options={
                'ordering': ['-fecha'],
            },
            bases=(finanzas.models.MontoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('tipo', models.CharField(choices=[('adm', 'Administraci\xf3n'), ('seg', 'Seguridad'), ('man', 'Mantenimiento')], max_length=3)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_servicio_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_servicio_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit')], max_length=1)),
                ('fecha', models.DateField()),
                ('decripcion', models.TextField(blank=True)),
                ('numero', models.CharField(blank=True, max_length=256)),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('monto_bruto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='humanos.Persona')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.Cuenta')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finanzas.Transaccion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
            bases=(finanzas.models.MontoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReciboMantenimiento',
            fields=[
                ('recibo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finanzas.Recibo')),
                ('recurrencias', recurrence.fields.RecurrenceField()),
            ],
            bases=('finanzas.recibo',),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.Recibo'),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Recibo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='finanzas.Servicio'),
        ),
    ]
