# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('banco', models.CharField(choices=[('BMX', 'Banamex'), ('BVA', 'BBVA Bancomer'), ('SAN', 'Santander'), ('HSB', 'HSBC'), ('BNT', 'Banorte'), ('IXE', 'Ixe banco')], max_length=64)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanos.Persona')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentabancaria_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuentabancaria_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
            },
        ),
    ]
