# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recurrencia', recurrence.fields.RecurrenceField()),
                ('tolerancia', models.DurationField(blank=True, null=True)),
                ('recargos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuota_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_cuota_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoCuotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_pagocuotas_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_de_cuotas', to='finanzas.CuentaBancaria')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.Cuota')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_pagocuotas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de cuota',
                'verbose_name_plural': 'pagos de cuotas',
            },
        ),
    ]
