# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_auto_20160705_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='cuentaempresarial',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cuentaempresarial',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='cuentapersonal',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cuentapersonal',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
    ]
