# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_auto_20160706_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='clabe',
            field=models.CharField(blank=True, help_text='Clave Bancaria Estandarizada', max_length=18, null=True, verbose_name='CLABE'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='numero',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='n\xfamero'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='referencias',
            field=models.TextField(blank=True),
        ),
    ]
