# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_auto_20160706_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='descripcion',
            field=models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='nombre',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='finanzas.Banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='humanos.Persona'),
        ),
    ]
