# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('tipo', models.CharField(choices=[('dep', 'Deportivo'), ('ent', 'Entretenimiento'), ('inf', 'Infantil'), ('fam', 'Familiar'), ('ser', 'Servicio'), ('otr', 'Otro')], max_length=3)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_actividad_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_actividad_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nombre', 'tipo'),
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, editable=False, verbose_name='descripci\xf3n')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('requiere_reservacion', models.BooleanField(verbose_name='require reservaci\xf3n')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dep\xf3sito en garant\xeda')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='capacidad m\xe1xima')),
                ('actividades', models.ManyToManyField(blank=True, related_name='amenidades', to='amenidades.Actividad')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_amenidad_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_amenidad_modificados', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominios.Nivel')),
            ],
            options={
                'ordering': ['nivel', 'nombre'],
                'verbose_name_plural': 'amenidades',
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('lunes_lunes', models.TimeField(blank=True, db_index=True, null=True)),
                ('lunes_martes', models.TimeField(blank=True, db_index=True, null=True)),
                ('lunes_miercoles', models.TimeField(blank=True, db_index=True, null=True, verbose_name='mi\xe9rcoles')),
                ('lunes_jueves', models.TimeField(blank=True, db_index=True, null=True)),
                ('lunes_viernes', models.TimeField(blank=True, db_index=True, null=True)),
                ('lunes_sabado', models.TimeField(blank=True, db_index=True, null=True, verbose_name='s\xe1bado')),
                ('lunes_domingo', models.TimeField(blank=True, db_index=True, null=True)),
                ('snacks', models.BooleanField(db_index=True, default=False)),
                ('alimentos', models.BooleanField(db_index=True, default=False)),
                ('alcohol', models.BooleanField(db_index=True, default=False)),
                ('ruido', models.BooleanField(db_index=True, default=False)),
                ('maximo_invitados', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='m\xe1ximo invitados')),
                ('edad_minima_acompanado', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Edad m\xednima para usar la amenidad acompa\xf1ado de un adulto', null=True, verbose_name='edad m\xednima (acompa\xf1ado)')),
                ('edad_minima_solo', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Edad m\xednima para usar la amenidad sin compa\xf1\xeda', null=True, verbose_name='edad m\xednima (solo)')),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='amenidades.Amenidad')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_regla_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_regla_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
