# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amenidades', '0002_cartelera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('cancelado', models.BooleanField(default=False)),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='amenidades.Amenidad')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_reservacion_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominios.Departamento')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenidades_reservacion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
