# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenidades', '0003_reservacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'ordering': ['-fecha_inicio', '-fecha_termino'], 'verbose_name': 'reservaci\xf3n', 'verbose_name_plural': 'reservaciones'},
        ),
    ]
