# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoestacionado',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='vehiculoestacionado',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
    ]
