# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humanos', '0003_auto_20160705_2230'),
        ('seguridad', '0003_auto_20160705_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino')),
                ('razon_termino', models.CharField(blank=True, max_length=255, null=True, verbose_name='raz\xf3n del t\xe9rmino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creaci\xf3n')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='\xfaltima modificaci\xf3n')),
                ('comentario', models.TextField()),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_comentario_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='iniciativa',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de la resoluci\xf3n'),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='resolucion',
            field=models.NullBooleanField(verbose_name='resoluci\xf3n'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='iniciativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seguridad.Iniciativa'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_comentario_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='humanos.Persona'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='seguridad.Comentario'),
        ),
    ]
