# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20160705_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_creacion', '-fecha_termino']},
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de t\xe9rmino'),
        ),
    ]
